# Generated by Django 3.2.5 on 2021-07-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_update_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Имя сетки')),
                ('task0', models.TextField(verbose_name='URL фото')),
                ('task1', models.TextField(verbose_name='URL фото')),
                ('task2', models.TextField(verbose_name='URL фото')),
                ('task3', models.TextField(verbose_name='URL фото')),
                ('task4', models.TextField(verbose_name='URL фото')),
                ('task5', models.TextField(verbose_name='URL фото')),
                ('task6', models.TextField(verbose_name='URL фото')),
                ('task7', models.TextField(verbose_name='URL фото')),
                ('task8', models.TextField(verbose_name='URL фото')),
                ('task9', models.TextField(verbose_name='URL фото')),
            ],
        ),
    ]
